### ISSUE TITLE
[Internal] Milestone management

### ISSUE THREAD

**Issue by VoNgocHieu** [AgoraIO/Docs-Source#1526]
### Details

1. 

### Take the following project management steps to fulfill this milestone:

- [X] Run the full scope of the proposed EN doc updates by the PO
- [X] Merge all PRs and close relevant tickets when the work is done
- [X] Create and share a Vercel instance for review and stakeholder signoff
- [X] Implement comments from stakeholders until fully resolved
- [X] Publish updates to https://docs.agora.io/en/
- [X] Inform the stakeholders
- [X] Close the milestone
