### ISSUE TITLE
Ashik[Internal] Milestone management

### ISSUE THREAD

**Issue by Ashikmia9500** [AgoraIO/Docs-Source#1544]
### Details

Adhik

### Take the following project management steps to fulfill this milestone:

- [X] Run the full scope of the proposed EN doc updates by the PO
- [ ] Merge all PRs and close relevant tickets when the work is done
- [ ] Create and share a Vercel instance for review and stakeholder signoff
- [ ] Implement comments from stakeholders until fully resolved
- [x] Publish updates to https://docs.agora.io/en/
- [ ] Inform the stakeholders
- [ ] Close the milestone

**Comment by Ashikmia9500** [comment]
Ok

**Comment by Ashikmia9500** [comment]
Y

**Comment by Ashikmia9500** [comment]
B

**Comment by Ashikmia9500** [comment]
G
