### ISSUE TITLE
Create the speech to text developer guide

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#885]
**Business case**: End users must easily implement speech recognition in their app

**Subject Matter Expert**: Cao,Yue

**Reviewers**:
  - *Technical*: Cao,Yue
  - *Language*: Iain
  - *PM*: 

**Scope**: 
    - A new doc using our standard template in the develop section for Video Calling, Interactive Live Streaming and Voice Calling called "Integrate speech recognition". This doc explains how to start and stop speech recognition in an app, then download and present the transcript. 
    - Use https://confluence.agoralab.co/display/PM/STT+Demo, https://docs-preprod.agora.io/en/live-streaming-premium-legacy/speech_to_text_rest?platform=Android, https://documenter.getpostman.com/view/6319646/SVSLr9AM#be07209a-8d90-40e8-8c20-86e1687a5012, https://confluence.agoralab.co/pages/viewpage.action?pageId=976159327.
    - Link to the API reference: https://documenter.getpostman.com/view/6319646/SVSLr9AM#be07209a-8d90-40e8-8c20-86e1687a5012
**Tasks**:
   - [x] @saudsami Create the initial doc and write the introduction, understand, Prerequisites, Project setup sections. 
   - [x] @saudsami Create the Android implementation and test section. 
   - [x] @nirm2009  Create the ios implementation and test section. 
   - [x]  @nirm2009  Create the macos implementation and test section. 
   - [x] @Kishan-Dhakan   Create the web implementation and test section. 
   - [x] @hussain-khalid  Create the windows implementation and test section. 
   - [x]  @hussain-khalid  Create the electron implementation and test section. 
   - [x] @hussain-khalid Create the unity implementation and test section. 
   - [x] @saudsami Create the flutter implementation and test section. 
   - [x] @Kishan-Dhakan Create the React Native implementation and test section. 

**Acceptance criteria**: Criteria for this issue to be approved.

**Additional valuable information**:  Branches for all tickets must be merged to https://github.com/AgoraIO/Docs-Source/tree/milestone37-speech-to-text.  The basic code is autogenerated in https://documenter.getpostman.com/view/6319646/SVSLr9AM#be07209a-8d90-40e8-8c20-86e1687a5012.

**Comment by billy-the-fish** [comment]
Done and ready for review.
